/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { locationLabelSchema } from "./locationLabelSchema.ts";
import { z } from "zod";

export const accountLocationLabelsResponseSchema = z.object({
  success: z.boolean().describe("Whether the request was successful"),
  payload: z
    .array(z.lazy(() => locationLabelSchema))
    .describe("List of location labels"),
});
