/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { locationAttributeSchema } from "./locationAttributeSchema.ts";
import { z } from "zod";

export const accountLocationProfileDataSchema = z.object({
  name: z.string().describe("Location name"),
  location_id: z.string().describe("Unique location identifier"),
  store_code: z.string().describe("Store code"),
  address: z.string().describe("Street address"),
  postal: z.optional(z.string().describe("Postal code")),
  city: z.string().describe("City name"),
  country_code: z.string().describe("Country code"),
  attribute_health: z.number().describe("Attribute health score"),
  attribute_json: z
    .array(z.lazy(() => locationAttributeSchema))
    .describe("Location attributes in JSON format"),
  description: z.string().describe("Business description"),
  category: z.string().describe("Primary business category"),
  additional_categories: z.optional(
    z.array(z.string()).describe("Additional business categories"),
  ),
  regular_hours: z.array(z.object({})).describe("Regular business hours"),
  special_hours: z.array(z.object({})).describe("Special business hours"),
  phone_number: z.string().describe("Primary phone number"),
  website_uri: z.string().url().describe("Website URL"),
  latitude: z.number().describe("Latitude coordinate"),
  longitude: z.number().describe("Longitude coordinate"),
});
