/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const errorSchema = z.object({
  code: z.string().describe("Error code"),
  message: z.string().describe("Human-readable error message"),
  details: z.optional(z.object({}).describe("Additional error details")),
  timestamp: z.optional(
    z.string().datetime().describe("When the error occurred"),
  ),
  requestId: z.optional(
    z.string().describe("Unique identifier for this request"),
  ),
});
