/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema.ts";
import { locationReviewFiltersSchema } from "./locationReviewFiltersSchema.ts";
import { reviewListResponseSchema } from "./reviewListResponseSchema.ts";
import { z } from "zod";

/**
 * @description Successful response
 */
export const getLocationReviews200Schema = z.lazy(
  () => reviewListResponseSchema,
);

/**
 * @description Bad request - invalid input data
 */
export const getLocationReviews400Schema = z.lazy(() => errorSchema);

/**
 * @description Unauthorized - invalid or missing authentication
 */
export const getLocationReviews401Schema = z.lazy(() => errorSchema);

/**
 * @description Internal server error
 */
export const getLocationReviews500Schema = z.lazy(() => errorSchema);

export const getLocationReviewsMutationRequestSchema = z.lazy(
  () => locationReviewFiltersSchema,
);

export const getLocationReviewsMutationResponseSchema = z.lazy(
  () => getLocationReviews200Schema,
);
