/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema.ts";
import { reviewFiltersSchema } from "./reviewFiltersSchema.ts";
import { reviewListResponseSchema } from "./reviewListResponseSchema.ts";
import { z } from "zod";

/**
 * @description Successful response
 */
export const getReviews200Schema = z.lazy(() => reviewListResponseSchema);

/**
 * @description Bad request - invalid input data
 */
export const getReviews400Schema = z.lazy(() => errorSchema);

/**
 * @description Unauthorized - invalid or missing authentication
 */
export const getReviews401Schema = z.lazy(() => errorSchema);

/**
 * @description Internal server error
 */
export const getReviews500Schema = z.lazy(() => errorSchema);

export const getReviewsMutationRequestSchema = z.lazy(
  () => reviewFiltersSchema,
);

export const getReviewsMutationResponseSchema = z.lazy(
  () => getReviews200Schema,
);
