/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { locationSchema } from "./locationSchema.ts";
import { z } from "zod";

export const locationListResponseSchema = z.object({
  success: z.boolean().describe("Whether the request was successful"),
  payload: z.object({
    metadata: z.object({
      pages: z.number().int().describe("Total number of pages"),
      results_per_page: z.number().int().describe("Number of results per page"),
      current_page: z.number().int().describe("Current page number"),
      results: z.number().int().describe("Total number of results"),
    }),
    data: z.array(z.lazy(() => locationSchema)),
  }),
});
