/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const locationLabelSchema = z.object({
  id: z.string().describe("Unique identifier for the label"),
  name: z.string().describe("Label name"),
  color: z.string().describe("Label color in hex format"),
  description: z.string().describe("Label description"),
});
