/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const locationReviewFiltersSchema = z.object({
  location_id: z.optional(z.string().describe("Google Location Id")),
  store_code: z.optional(
    z
      .string()
      .describe(
        "Location Store Code. Can be provided in place of a Location Id",
      ),
  ),
  star_rating: z.optional(
    z.number().int().min(1).max(5).describe("Review rating between 1 to 5"),
  ),
  has_comment: z.optional(z.boolean().describe("If review has response")),
  is_deleted: z.optional(
    z.boolean().describe("If review has been deleted from Google"),
  ),
  page: z.optional(z.number().describe("Page number")),
  per_page: z.optional(
    z
      .number()
      .max(50)
      .default(10)
      .describe("Results per page. Default is 10. Maximum is 50"),
  ),
});
