/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { errorSchema } from "./errorSchema.ts";
import { reviewReplyRequestSchema } from "./reviewReplyRequestSchema.ts";
import { reviewReplyResponseSchema } from "./reviewReplyResponseSchema.ts";
import { z } from "zod";

export const replyToReviewPathParamsSchema = z.object({
  reviewId: z.string().describe("Unique identifier for the review"),
});

/**
 * @description Reply created successfully
 */
export const replyToReview201Schema = z.lazy(() => reviewReplyResponseSchema);

/**
 * @description Bad request - invalid input data
 */
export const replyToReview400Schema = z.lazy(() => errorSchema);

/**
 * @description Unauthorized - invalid or missing authentication
 */
export const replyToReview401Schema = z.lazy(() => errorSchema);

/**
 * @description Not found - requested resource does not exist
 */
export const replyToReview404Schema = z.lazy(() => errorSchema);

/**
 * @description Internal server error
 */
export const replyToReview500Schema = z.lazy(() => errorSchema);

export const replyToReviewMutationRequestSchema = z.lazy(
  () => reviewReplyRequestSchema,
);

export const replyToReviewMutationResponseSchema = z.lazy(
  () => replyToReview201Schema,
);
