/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { reviewReplySchema } from "./reviewReplySchema.ts";
import { z } from "zod";

export const reviewSchema = z.object({
  id: z.string().describe("Unique identifier for the review"),
  customerName: z.string().describe("Name of the customer who left the review"),
  customerPhoto: z.optional(
    z.string().url().describe("URL to customer's profile photo"),
  ),
  rating: z.number().int().min(1).max(5).describe("Star rating (1-5)"),
  comment: z.string().describe("Review text content"),
  date: z.string().datetime().describe("Date when the review was posted"),
  locationId: z.string().describe("ID of the location this review is for"),
  locationName: z.optional(z.string().describe("Name of the location")),
  status: z
    .enum(["new", "replied", "hidden", "flagged"])
    .describe("Current status of the review"),
  businessReply: z.optional(z.lazy(() => reviewReplySchema)),
  helpfulVotes: z.optional(
    z.number().int().min(0).describe("Number of helpful votes"),
  ),
  photos: z.optional(
    z.array(z.string().url()).describe("URLs to photos attached to the review"),
  ),
});
