/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const reviewSuggestionResponseSchema = z.object({
  msg: z.array(
    z.object({
      index: z.number().int().describe("Index of the message"),
      message: z.object({
        role: z.string().describe("Role of the message sender"),
        content: z
          .string()
          .describe("AI-generated reply suggestion for the review"),
        annotations: z.optional(
          z.array(z.object({})).describe("Additional annotations"),
        ),
        refusal: z.string().describe("Refusal reason if any").nullish(),
      }),
      logprobs: z.nullable(z.string().describe("Log probabilities")),
      finish_reason: z.string().describe("Reason for finishing the response"),
    }),
  ),
});
