/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const reviewReplyRequestSchema = z.object({
  text: z.string().min(1).max(1000).describe("Reply text content"),
  isPublic: z.optional(
    z
      .boolean()
      .default(true)
      .describe("Whether the reply should be visible to the public"),
  ),
});
