/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const reviewReplySchema = z.object({
  id: z.string().describe("Unique identifier for the reply"),
  text: z.string().describe("Reply text content"),
  date: z.string().datetime().describe("Date when the reply was posted"),
  isPublic: z.boolean().describe("Whether the reply is visible to the public"),
  author: z.optional(
    z.string().describe("Name of the person who wrote the reply"),
  ),
});
