/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";

export const reviewFiltersSchema = z.object({
  star_rating: z.optional(
    z.number().int().min(1).max(5).describe("Review rating between 1 to 5"),
  ),
  has_comment: z.optional(z.boolean().describe("If review has response")),
  has_reply: z.optional(
    z.boolean().describe("If review has a business reply (reply field = 1)"),
  ),
  is_deleted: z.optional(
    z.boolean().describe("If review has been deleted from Google"),
  ),
  page: z.optional(z.number().describe("Page number")),
  per_page: z.optional(
    z
      .number()
      .max(50)
      .default(10)
      .describe("Results per page. Default is 10. Maximum is 50"),
  ),
});
