/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LocationAttribute } from "./LocationAttribute.ts";

export type AccountLocationProfileData = {
  /**
   * @description Location name
   * @type string
   */
  name: string;
  /**
   * @description Unique location identifier
   * @type string
   */
  location_id: string;
  /**
   * @description Store code
   * @type string
   */
  store_code: string;
  /**
   * @description Street address
   * @type string
   */
  address: string;
  /**
   * @description Postal code
   * @type string | undefined
   */
  postal?: string;
  /**
   * @description City name
   * @type string
   */
  city: string;
  /**
   * @description Country code
   * @type string
   */
  country_code: string;
  /**
   * @description Attribute health score
   * @type number, float
   */
  attribute_health: number;
  /**
   * @description Location attributes in JSON format
   * @type array
   */
  attribute_json: LocationAttribute[];
  /**
   * @description Business description
   * @type string
   */
  description: string;
  /**
   * @description Primary business category
   * @type string
   */
  category: string;
  /**
   * @description Additional business categories
   * @type array | undefined
   */
  additional_categories?: string[];
  /**
   * @description Regular business hours
   * @type array
   */
  regular_hours: object[];
  /**
   * @description Special business hours
   * @type array
   */
  special_hours: object[];
  /**
   * @description Primary phone number
   * @type string
   */
  phone_number: string;
  /**
   * @description Website URL
   * @type string, uri
   */
  website_uri: string;
  /**
   * @description Latitude coordinate
   * @type number, float
   */
  latitude: number;
  /**
   * @description Longitude coordinate
   * @type number, float
   */
  longitude: number;
};
