/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LocationLabel } from "./LocationLabel.ts";

export type AccountLocationLabelsResponse = {
  /**
   * @description Whether the request was successful
   * @type boolean
   */
  success: boolean;
  /**
   * @description List of location labels
   * @type array
   */
  payload: LocationLabel[];
};
