/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Error = {
  /**
   * @description Error code
   * @type string
   */
  code: string;
  /**
   * @description Human-readable error message
   * @type string
   */
  message: string;
  /**
   * @description Additional error details
   * @type object | undefined
   */
  details?: object;
  /**
   * @description When the error occurred
   * @type string | undefined, date-time
   */
  timestamp?: string;
  /**
   * @description Unique identifier for this request
   * @type string | undefined
   */
  requestId?: string;
};
