/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AccountKPIsResponse } from "./AccountKPIsResponse.ts";
import type { Error } from "./Error.ts";

/**
 * @description Successful response with account KPIs
 */
export type GetAccountKPIs200 = AccountKPIsResponse;

/**
 * @description Bad request - invalid input data
 */
export type GetAccountKPIs400 = Error;

/**
 * @description Unauthorized - invalid or missing authentication
 */
export type GetAccountKPIs401 = Error;

/**
 * @description Internal server error
 */
export type GetAccountKPIs500 = Error;

export type GetAccountKPIsQueryResponse = GetAccountKPIs200;

export type GetAccountKPIsQuery = {
  Response: GetAccountKPIs200;
  Errors: GetAccountKPIs400 | GetAccountKPIs401 | GetAccountKPIs500;
};
