/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AccountLocationLabelsResponse } from "./AccountLocationLabelsResponse.ts";
import type { Error } from "./Error.ts";

/**
 * @description Successful response with location labels
 */
export type GetAccountLocationLabels200 = AccountLocationLabelsResponse;

/**
 * @description Bad request - invalid input data
 */
export type GetAccountLocationLabels400 = Error;

/**
 * @description Unauthorized - invalid or missing authentication
 */
export type GetAccountLocationLabels401 = Error;

/**
 * @description Internal server error
 */
export type GetAccountLocationLabels500 = Error;

export type GetAccountLocationLabelsQueryResponse = GetAccountLocationLabels200;

export type GetAccountLocationLabelsQuery = {
  Response: GetAccountLocationLabels200;
  Errors:
    | GetAccountLocationLabels400
    | GetAccountLocationLabels401
    | GetAccountLocationLabels500;
};
