/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error.ts";
import type { LocationListResponse } from "./LocationListResponse.ts";

export type GetLocationsQueryParams = {
  /**
   * @description Page number
   * @minLength 1
   * @default 1
   * @type integer | undefined
   */
  page?: number;
  /**
   * @description Results per page. Default is 10. Maximum is 50
   * @minLength 1
   * @maxLength 50
   * @default 10
   * @type integer | undefined
   */
  per_page?: number;
  /**
   * @description Filter locations based on store code
   * @type string | undefined
   */
  store_code?: string;
  /**
   * @description Select the fields to include based on the Location object
   * @type string | undefined
   */
  include_fields?: string;
};

/**
 * @description Successful response with locations list
 */
export type GetLocations200 = LocationListResponse;

/**
 * @description Bad request - invalid input data
 */
export type GetLocations400 = Error;

/**
 * @description Unauthorized - invalid or missing authentication
 */
export type GetLocations401 = Error;

/**
 * @description Internal server error
 */
export type GetLocations500 = Error;

export type GetLocationsQueryResponse = GetLocations200;

export type GetLocationsQuery = {
  Response: GetLocations200;
  QueryParams: GetLocationsQueryParams;
  Errors: GetLocations400 | GetLocations401 | GetLocations500;
};
