/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error.ts";
import type { ReviewSuggestionRequest } from "./ReviewSuggestionRequest.ts";
import type { ReviewSuggestionResponse } from "./ReviewSuggestionResponse.ts";

/**
 * @description Successful response with suggestion
 */
export type GetReviewSuggestion200 = ReviewSuggestionResponse;

/**
 * @description Bad request - invalid input data
 */
export type GetReviewSuggestion400 = Error;

/**
 * @description Unauthorized - invalid or missing authentication
 */
export type GetReviewSuggestion401 = Error;

/**
 * @description Internal server error
 */
export type GetReviewSuggestion500 = Error;

export type GetReviewSuggestionMutationRequest = ReviewSuggestionRequest;

export type GetReviewSuggestionMutationResponse = GetReviewSuggestion200;

export type GetReviewSuggestionMutation = {
  Response: GetReviewSuggestion200;
  Request: GetReviewSuggestionMutationRequest;
  Errors:
    | GetReviewSuggestion400
    | GetReviewSuggestion401
    | GetReviewSuggestion500;
};
