/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Location } from "./Location.ts";

export type LocationListResponse = {
  /**
   * @description Whether the request was successful
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  payload: {
    /**
     * @type object
     */
    metadata: {
      /**
       * @description Total number of pages
       * @type integer
       */
      pages: number;
      /**
       * @description Number of results per page
       * @type integer
       */
      results_per_page: number;
      /**
       * @description Current page number
       * @type integer
       */
      current_page: number;
      /**
       * @description Total number of results
       * @type integer
       */
      results: number;
    };
    /**
     * @type array
     */
    data: Location[];
  };
};
