/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LocationAttributes = {
  /**
   * @description List of missing attributes
   * @type array
   */
  missing_attributes: string[];
  /**
   * @description List of available attributes
   * @type array
   */
  available_attributes: string[];
};
