/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Error } from "./Error.ts";
import type { ReviewReplyRequest } from "./ReviewReplyRequest.ts";
import type { ReviewReplyResponse } from "./ReviewReplyResponse.ts";

export type ReplyToReviewPathParams = {
  /**
   * @description Unique identifier for the review
   * @type string
   */
  reviewId: string;
};

/**
 * @description Reply created successfully
 */
export type ReplyToReview201 = ReviewReplyResponse;

/**
 * @description Bad request - invalid input data
 */
export type ReplyToReview400 = Error;

/**
 * @description Unauthorized - invalid or missing authentication
 */
export type ReplyToReview401 = Error;

/**
 * @description Not found - requested resource does not exist
 */
export type ReplyToReview404 = Error;

/**
 * @description Internal server error
 */
export type ReplyToReview500 = Error;

export type ReplyToReviewMutationRequest = ReviewReplyRequest;

export type ReplyToReviewMutationResponse = ReplyToReview201;

export type ReplyToReviewMutation = {
  Response: ReplyToReview201;
  Request: ReplyToReviewMutationRequest;
  PathParams: ReplyToReviewPathParams;
  Errors:
    | ReplyToReview400
    | ReplyToReview401
    | ReplyToReview404
    | ReplyToReview500;
};
