/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ReviewSummary = {
  /**
   * @description Total number of reviews matching filters
   * @type integer
   */
  total: number;
  /**
   * @description Average rating of filtered reviews
   * @minLength 1
   * @maxLength 5
   * @type number, float
   */
  averageRating: number;
  /**
   * @description Distribution of ratings (1-5 stars)
   * @type object
   */
  ratingDistribution: {
    /**
     * @type integer | undefined
     */
    "1"?: number;
    /**
     * @type integer | undefined
     */
    "2"?: number;
    /**
     * @type integer | undefined
     */
    "3"?: number;
    /**
     * @type integer | undefined
     */
    "4"?: number;
    /**
     * @type integer | undefined
     */
    "5"?: number;
  };
};
