/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ReviewReply = {
  /**
   * @description Unique identifier for the reply
   * @type string
   */
  id: string;
  /**
   * @description Reply text content
   * @type string
   */
  text: string;
  /**
   * @description Date when the reply was posted
   * @type string, date-time
   */
  date: string;
  /**
   * @description Whether the reply is visible to the public
   * @type boolean
   */
  isPublic: boolean;
  /**
   * @description Name of the person who wrote the reply
   * @type string | undefined
   */
  author?: string;
};
